from pathlib import Path
from collections import deque
from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "logo_assets.c"
SIZE = 28

IMAGES = [
    ("codex_logo", ROOT / "imgs" / "codex.png", (255, 255, 255), "dark_strokes"),
    ("claude_logo", ROOT / "imgs" / "claudecode.png", (246, 183, 60), "solid_shape"),
]


def rgba_to_lv_bytes(pixel):
    r, g, b, a = pixel
    rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    return (rgb565 & 0xFF, (rgb565 >> 8) & 0xFF, a)


def luminance(pixel):
    r, g, b, _ = pixel
    return (r * 299 + g * 587 + b * 114) // 1000


def background_mask(img):
    width, height = img.size
    pixels = img.load()
    seen = [[False] * width for _ in range(height)]
    queue = deque()

    def is_dark(x, y):
        return pixels[x, y][3] > 20 and luminance(pixels[x, y]) < 40

    for x in range(width):
        for y in (0, height - 1):
            if is_dark(x, y) and not seen[y][x]:
                seen[y][x] = True
                queue.append((x, y))
    for y in range(height):
        for x in (0, width - 1):
            if is_dark(x, y) and not seen[y][x]:
                seen[y][x] = True
                queue.append((x, y))

    while queue:
        x, y = queue.popleft()
        for nx, ny in ((x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1)):
            if 0 <= nx < width and 0 <= ny < height and not seen[ny][nx] and is_dark(nx, ny):
                seen[ny][nx] = True
                queue.append((nx, ny))

    return seen


def recolor_icon(path, color, mode):
    source = Image.open(path).convert("RGBA")
    bg = background_mask(source)
    width, height = source.size
    pixels = source.load()
    out = Image.new("RGBA", source.size, (0, 0, 0, 0))
    out_pixels = out.load()

    for y in range(height):
        for x in range(width):
            pixel = pixels[x, y]
            alpha = pixel[3]
            if alpha <= 8 or bg[y][x]:
                continue

            light = luminance(pixel)
            if mode == "dark_strokes":
                if light >= 150:
                    continue
                alpha = max(0, min(255, int((170 - light) * 2.2)))
            elif mode == "solid_shape":
                if light < 45:
                    continue

            out_pixels[x, y] = (*color, alpha)

    return out


def image_bytes(path, color, mode):
    img = recolor_icon(path, color, mode)
    img.thumbnail((SIZE, SIZE), Image.Resampling.LANCZOS)

    canvas = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    x = (SIZE - img.width) // 2
    y = (SIZE - img.height) // 2
    canvas.alpha_composite(img, (x, y))

    values = []
    for pixel in canvas.getdata():
        values.extend(rgba_to_lv_bytes(pixel))
    return values


def write_array(f, name, values):
    f.write(f"static const uint8_t {name}_map[] = {{\n")
    for i in range(0, len(values), 18):
        chunk = values[i : i + 18]
        f.write("  " + ", ".join(f"0x{value:02X}" for value in chunk) + ",\n")
    f.write("};\n\n")
    f.write(f"const lv_img_dsc_t {name} = {{\n")
    f.write("  .header.always_zero = 0,\n")
    f.write(f"  .header.w = {SIZE},\n")
    f.write(f"  .header.h = {SIZE},\n")
    f.write("  .data_size = sizeof(" + name + "_map),\n")
    f.write("  .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,\n")
    f.write("  .data = " + name + "_map,\n")
    f.write("};\n\n")


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8", newline="\n") as f:
        f.write("// Generated by scripts/generate_logo_assets.py. Do not edit by hand.\n")
        f.write("#include <lvgl.h>\n\n")
        for name, path, color, mode in IMAGES:
            write_array(f, name, image_bytes(path, color, mode))


if __name__ == "__main__":
    main()
